In [1]:
import numpy as np
matrix = np.matrix("1,5,7;2,6,9;4,8,3")
multiple = matrix * 2
print(multiple)
multiple[multiple > 10] = 0
print(multiple)

[[ 2 10 14]
 [ 4 12 18]
 [ 8 16  6]]
[[ 2 10  0]
 [ 4  0  0]
 [ 8  0  6]]


In [3]:
arr = np.random.randint(1, 101, 20)
print(arr)
div_5 = arr[arr % 5 == 0]
print("элементы, которые делятся на 5 без остатка:\n", div_5)
arr[arr % 5 == 0] = -1
print("Обновлённый массив:\n", arr)

[97 95 11 25 39  6 12 71 52 25  7 63 20 85 97 28  6 41 34 42]
элементы, которые делятся на 5 без остатка:
 [95 25 25 20 85]
Обновлённый массив:
 [97 -1 11 -1 39  6 12 71 52 -1  7 63 -1 -1 97 28  6 41 34 42]


In [5]:
a = np.random.randint(0, 51, 5)
print("Первый массив:\n", a)
b = np.random.randint(0, 51, 5)
print("Второй массив:\n", b)
ab = np.vstack((a,b))
print("Объединенный массив:\n", ab)
a1, b1 = np.vsplit(ab, 2)
print("Разделенные массивы:\nПервый:", a1, "\nВторой:", b1)

Первый массив:
 [29 14 49 20 36]
Второй массив:
 [37 28 16 31 23]
Объединенный массив:
 [[29 14 49 20 36]
 [37 28 16 31 23]]
Разделенные массивы:
Первый: [[29 14 49 20 36]] 
Второй: [[37 28 16 31 23]]


In [7]:
a = np.random.randint(-10, 11, 50)
print("Созданный массив: ", a)
summ_all = np.sum(a)
print("Сумма всех элементов: ", summ_all)
pos_summ = np.sum(a[a > 0])
print("Сумма положительных элементов: ", pos_summ)
neg_summ = np.sum(a[a < 0])
print("Сумма отрицательных элементов: ", neg_summ)

Созданный массив:  [ -8   7  -1  -6  -1   2  10   0  -2  -2  -8   0   4  -7  -9  -8  -3  -8
   4  -3  -4   8 -10   8  -8  -6   7  -4  -2  -9   0   0   4  -7   1  -2
  -4  -7  -3   5   9   5   9  10  10   8  -1   4   4  -4]
Сумма всех элементов:  -18
Сумма положительных элементов:  119
Сумма отрицательных элементов:  -137


In [9]:
edm = np.identity(4)
print("Единичная матрица: \n", edm)
diagm = np.diag([5, 10, 15, 20])
print("Диагональная матрица:\n", diagm)
edm_summ = np.sum(edm)
print("Сумма элементов единичной матрицы:\n", edm_summ)
diagm_summ = np.sum(diagm)
print("Сумма элементов диагональной матрицы:\n", diagm_summ)
print("По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.")

Единичная матрица: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы:
 4.0
Сумма элементов диагональной матрицы:
 50
По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.


In [11]:
a = np.random.randint(1, 21, (3, 3))
print("Первая матрица:\n", a)
b = np.random.randint(1, 21, (3, 3))
print("Вторая матрица:\n", b)
summ = a + b
print("Сумма: ", summ)
razn = a - b
print("Разница: ", razn)
proz = a * b
print("Произведение: ", proz)

Первая матрица:
 [[11  5 15]
 [ 9 19 18]
 [10 11  1]]
Вторая матрица:
 [[ 4 14 12]
 [12 15 13]
 [13 15  1]]
Сумма:  [[15 19 27]
 [21 34 31]
 [23 26  2]]
Разница:  [[ 7 -9  3]
 [-3  4  5]
 [-3 -4  0]]
Произведение:  [[ 44  70 180]
 [108 285 234]
 [130 165   1]]


In [13]:
a = np.random.randint(1, 11, (2, 3))
print("Первая матрица:\n", a)
b = np.random.randint(1, 11, (3, 2))
print("Вторая матрица:\n", b)
mult = a @ b
print("Матричное умножение:\n", mult)

Первая матрица:
 [[6 8 8]
 [1 7 4]]
Вторая матрица:
 [[ 5  6]
 [ 1 10]
 [ 7  4]]
Матричное умножение:
 [[ 94 148]
 [ 40  92]]


In [15]:
a = np.random.randint(1, 21, (3, 3))
print("Матрица:\n", a)
det = np.linalg.det(a)
print("Определитель:\n", det)
if np.isclose(det, 0):
    inv = "Матрица вырождена"
else:
    inv = np.linalg.inv(a)
print("Обратная матрица:\n", inv)

Матрица:
 [[10 18 19]
 [ 5 11  9]
 [19 16 12]]
Определитель:
 -572.9999999999997
Обратная матрица:
 [[ 0.02094241 -0.15357766  0.08202443]
 [-0.19371728  0.42059337 -0.008726  ]
 [ 0.22513089 -0.31762653 -0.03490401]]


In [17]:
a = np.random.randint(1, 51, (4, 4))
print("Матрица:\n", a)
transp = a.T
print("Транспонированная матрица:\n", transp)
value = np.trace(a)
print("След матрицы:\n", value)

Матрица:
 [[23 34 32 31]
 [ 1  6 48 22]
 [35 11 47 15]
 [39  1 47 38]]
Транспонированная матрица:
 [[23  1 35 39]
 [34  6 11  1]
 [32 48 47 47]
 [31 22 15 38]]
След матрицы:
 114


In [19]:
A = np.array([[2, 3, -1],
             [4, -1, 2],
             [-3, 5, 4]])
B = np.array([5, 6, -2])
res = np.linalg.solve(A, B)
print("Решение системы: ", res)

Решение системы:  [1.63963964 0.57657658 0.00900901]


В диете необходимо включить три продукта: мясо, рыбу и овощи. Они содержат белки, жиры и углеводы в разном количестве. В 100 г мяса содержится 20 г белков, 10 г жиров и 5 г углеводов, в 100 г рыбы — 15 г белков, 5 г жиров и 10 г углеводов, в 100 г овощей — 5 г белков, 2 г жиров и 20 г углеводов. Суточная норма: 100 г белков, 50 г жиров и 150 г углеводов. Сколько граммов каждого продукта нужно съесть?

In [1]:
import numpy as np

# Матрица содержания питательных веществ в продуктах (белки, жиры, углеводы)
A = np.array([[20, 15, 5],   # Белки
              [10, 5, 2],    # Жиры
              [5, 10, 20]])  # Углеводы

# Вектор суточной нормы питательных веществ
B = np.array([100, 50, 150])  # Белки, жиры, углеводы

# Решение системы уравнений методом Крамера
det_A = np.linalg.det(A)
if det_A != 0:
    kram1 = np.linalg.det(np.column_stack([B, A[:, 1], A[:, 2]])) / det_A
    kram2 = np.linalg.det(np.column_stack([A[:, 0], B, A[:, 2]])) / det_A
    kram3 = np.linalg.det(np.column_stack([A[:, 0], A[:, 1], B])) / det_A
    kramer = np.array([kram1, kram2, kram3])
else:
    kramer = "не применим"

# Решение методом матричного уравнения
if det_A == 0:
    matrix = "не применим"
else:
    matrix = np.linalg.inv(A).dot(B)

# Решение системы уравнений средствами библиотеки NumPy
try:
    numpy_solution = np.linalg.solve(A, B)
except np.linalg.LinAlgError:
    numpy_solution = "не применим"

print("Метод Крамера: ", kramer)
print("Метод матричного уравнения: ", matrix)
print("Библиотека NumPy: ", numpy_solution)

Метод Крамера:  [ 4.28571429 -1.42857143  7.14285714]
Метод матричного уравнения:  [ 4.28571429 -1.42857143  7.14285714]
Библиотека NumPy:  [ 4.28571429 -1.42857143  7.14285714]
